import { Poppins, Tienne } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  variable: "---font-poppins",
  weight: ['400', '700']
})

const tienne = Tienne({
  variable: "--font-tienne",
  weight: ["400", "700"], // specify weights you need
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        className={`${tienne.variable} ${poppins.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
